.github/workflows/build_snatch.yml, CODEOWNERS
Add the image building job for Snatch
- add the image building job for Snatch
=> GitHub Actions, build-job for Snatch 

sec-scanners-config.yaml
- security scanners configuration added to project
- https://github.com/kyma-project/infrastructure-manager/issues/396
=> Add security scanners configuration

sec-scanners-config.yaml
- scanners configured to use latest snatch images
- https://github.com/kyma-project/infrastructure-manager/issues/396
=> Configure scanners to follow latest snatch image

sec-scanners-config.yaml
Adjusting module name after alignment with release management.
=> Update module name in sec-config

sec-scanners-config.yaml
Updating image name in sec-config.
=> Adjust image name

Makefile, config/manager/kustomization.yaml, sec-scanners-config.yaml
- update scanners configuration
=> Update scanners configuration

internal/webhook/server/server.go
=> Remove race condition in go-routine

internal/webhook/server/server.go
=> fix race condition

internal/webhook/server/server.go
- refactor webhook server
- https://github.com/kyma-project/infrastructure-manager/issues/396
=> Refactor webhook server

sec-scanners-config.yaml
- security scanners configuration for release 0.0.5 bumped
=> Bump security scanners configuration for release 0.0.5

sec-scanners-config.yaml
- security scanners configuration updated for release 0.0.6
=> Bump security scanners configuration for release 0.0.6

sec-scanners-config.yaml
- prepare sec scanners to release 0.0.7
=> Update security configs to the latest release

config/default/kustomization.yaml, config/k3d/kustomization.yaml
- Delete Kustomize patch for metrics endpoint because it is no longer needed #45 
=> Delete Kustomize patch for metrics endpoint

sec-scanners-config.yaml
Bump security scanners configuration for release 1.0.0
- security scanners configuration for release 1.0.0 bumped
=> Bump security scanners configuration for release 1.0.0

.github/workflows/tests.yml, config/certmanager/certificate.yaml, config/default/manager_webhook_patch.yaml, config/gardener/certmanager/certificate.yaml, config/k3d/kustomization.yaml, config/k3d/manager_webhook_patch.yaml, sec-scanners-config.yaml, test/e2e/e2e_test.go
- fix error handling in pipeline
- fix invalid case in e2e test scenario
=> Fix controller e2e tests

.github/workflows/vuln-check.yaml, go.mod, go.sum
- Update golang.org/x/oauth2 to v0.29.0
- update vuln-check workflow
- update go to v1.24.2
=> Update golang.org/x/oauth2 to v0.29.0

sec-scanners-config.yaml
- Change bdba scanned image tag to latest
=> Change bdba scanned image tag to latest

config/manager/kustomization.yaml, config/manager/priority_class.yaml, config/manager/priority_class_patch.yaml, sec-scanners-config.yaml, test/e2e/e2e_test.go
- Priority class added
- https://github.com/kyma-project/kim-snatch/issues/123
=> Add priority-class

api/v1beta1/registryconfig_types.go
- Fix in a function setting Ready status
#965
=> Fix setting Ready status on Registry Cache CR

.github/workflows/build_snatch.yml
- add experimental tag during build 
- ...
- ...
- internal/7573
- ([link](https://github.com/kyma-project/application-connector-manager/pull/617))
=> add experimental tag during build

.github/workflows/build_snatch.yml
- **fix default value if tag is not set**
- ...
- ...
#195
=> experimental tag
